import type { Metadata } from "next";
import { ASSET_IDS } from "@/lib/dam/asset-ids";
import {
  damMetadataImage,
  damTwitterImages,
  type DamMetadataImage,
} from "@/lib/dam/site-images";
import { COMPANY } from "@/lib/company";

/**
 * Institutional homepage / default social copy.
 * Visual OG art is generated by scripts/generate-og-brand.mjs
 */
export const SITE_SEO = {
  defaultTitle: "PremiumCare ApS | Professionel og personlig omsorg",
  defaultDescription:
    "PremiumCare ApS leverer professionel, nærværende og værdig omsorg med udgangspunkt i det enkelte menneskes behov.",
  openGraphTitle: "Pleje, der føles trygt",
  openGraphDescription:
    "Professionel, personlig og værdig pleje fra PremiumCare ApS.",
  openGraphImageAlt:
    "PremiumCare ApS – professionel og værdig omsorg med mennesket i centrum",
} as const;

export type PageMetadataInput = {
  /** Document / browser title (without template suffix when absolute) */
  title: string;
  description: string;
  /** Path beginning with /, e.g. "/" or "/om-os" */
  path: string;
  /** Optional Open Graph / Twitter title override */
  openGraphTitle?: string;
  openGraphDescription?: string;
  /** DAM asset ID for social image — defaults to institutional brand OG */
  imageAssetId?: string;
  /** Absolute image alt override */
  imageAlt?: string;
  type?: "website" | "article";
  /** When true, title is used as-is (no layout template) */
  absoluteTitle?: boolean;
};

function canonicalUrl(path: string): string {
  if (path === "/") return COMPANY.url;
  const normalized = path.startsWith("/") ? path : `/${path}`;
  return `${COMPANY.url}${normalized}`;
}

function resolveSocialImage(
  assetId: string,
  altOverride?: string,
): DamMetadataImage {
  const image = damMetadataImage(assetId);
  if (altOverride) {
    return { ...image, alt: altOverride };
  }
  if (assetId === ASSET_IDS.brandOpenGraph) {
    return { ...image, alt: SITE_SEO.openGraphImageAlt };
  }
  return image;
}

/**
 * Build page metadata that inherits site defaults and allows
 * title, description, social image, and canonical overrides.
 */
export function buildPageMetadata(input: PageMetadataInput): Metadata {
  const imageAssetId = input.imageAssetId ?? ASSET_IDS.brandOpenGraph;
  const image = resolveSocialImage(imageAssetId, input.imageAlt);
  const ogTitle = input.openGraphTitle ?? input.title;
  const ogDescription = input.openGraphDescription ?? input.description;
  const url = canonicalUrl(input.path);

  return {
    title: input.absoluteTitle
      ? { absolute: input.title }
      : input.title,
    description: input.description,
    alternates: {
      canonical: input.path === "/" ? "/" : input.path,
    },
    openGraph: {
      type: input.type ?? "website",
      siteName: COMPANY.legalName,
      locale: "da_DK",
      title: ogTitle,
      description: ogDescription,
      url,
      images: [image],
    },
    twitter: {
      card: "summary_large_image",
      title: ogTitle,
      description: ogDescription,
      images: damTwitterImages(imageAssetId),
    },
  };
}

export function defaultSiteMetadata(): Metadata {
  return {
    ...buildPageMetadata({
      title: SITE_SEO.defaultTitle,
      description: SITE_SEO.defaultDescription,
      path: "/",
      openGraphTitle: SITE_SEO.openGraphTitle,
      openGraphDescription: SITE_SEO.openGraphDescription,
      imageAssetId: ASSET_IDS.brandOpenGraph,
      absoluteTitle: true,
    }),
    metadataBase: new URL(COMPANY.url),
    title: {
      default: SITE_SEO.defaultTitle,
      template: `%s · ${COMPANY.brandName}`,
    },
  };
}
